'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import type { AttendanceReviewListResult, AttendanceReviewSegment, AttendanceReviewExclusion } from '../../../../../../packages/contracts/src/attendance-review';
import styles from './review.module.css';
type Employee={id:string;workplaceId:string;displayName:string};
type View=AttendanceReviewListResult&{candidate?:{segments:readonly AttendanceReviewSegment[];exclusions:readonly AttendanceReviewExclusion[];reason:string}|null};
const labels={ordinary:'Giờ làm thường',holiday_daytime:'Giờ ngày lễ',out_of_schedule:'Ngoài lịch',night_work:'Giờ ban đêm'};
const formatter=new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3,hourCycle:'h23'});
const time=(ms:number)=>formatter.format(new Date(ms));
const localInput=(ms:number)=>new Date(ms+7*3600000).toISOString().slice(0,23);
const fromLocal=(value:string)=>Date.parse(value+'+07:00');
function priorMonth(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit'}).formatToParts(new Date());const year=Number(parts.find(p=>p.type==='year')?.value),month=Number(parts.find(p=>p.type==='month')?.value);return new Date(Date.UTC(year,month-2,1)).toISOString().slice(0,7);}
const errors:Record<string,string>={SOURCE_HASH_STALE:'Dữ liệu nguồn đã thay đổi. Tải lại và lập đề xuất mới.',STALE_VERSION:'Một người khác vừa cập nhật. Tải lại bảng công.',CANDIDATE_HASH_STALE:'Đề xuất đã thay đổi. Tải lại để kiểm tra.',REVIEW_BLOCKED:'Còn dữ liệu chưa được xử lý. Kiểm tra các mục cần xử lý.',FRESH_TOTP_REQUIRED:'Cần xác thực lại trước khi phê duyệt.',FORBIDDEN:'Tài khoản này không được thực hiện thao tác.',SEGMENT_OVERLAP:'Các khoảng thời gian đang chồng nhau.',RAW_EVENT_DISPOSITION_INVALID:'Mỗi chấm công gốc phải được xử lý đúng một lần.',CORRECTION_REQUIRES_REASON:'Cần lý do rõ ràng cho điều chỉnh.'};
export default function ReviewPanel(){
 const [session,setSession]=useState<{csrfToken:string;actor:{role:'owner'|'accountant'}}|null>(null),[loaded,setLoaded]=useState(false),[employees,setEmployees]=useState<Employee[]>([]),[employeeId,setEmployeeId]=useState(''),[month,setMonth]=useState(priorMonth),[view,setView]=useState<View|null>(null),[segments,setSegments]=useState<AttendanceReviewSegment[]>([]),[excluded,setExcluded]=useState<string[]>([]),[reason,setReason]=useState(''),[approvalReason,setApprovalReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;void(async()=>{try{const r=await fetch('/api/auth/session',{cache:'no-store'});if(!r.ok)return;const s=await r.json();if(!active)return;setSession(s);const list=await fetch('/api/attendance?list=employees',{cache:'no-store'});if(!list.ok)throw Error();const data=await list.json();if(active){setEmployees(data.employees);setEmployeeId(data.employees[0]?.id??'');}}catch{if(active)setMessage('Chưa tải được danh sách. Vui lòng thử lại.');}finally{if(active)setLoaded(true);}})();return()=>{active=false};},[]);
 const employee=employees.find(e=>e.id===employeeId);
 async function load(){if(!employee)return;setBusy(true);try{const q=new URLSearchParams({employeeId,workplaceId:employee.workplaceId,month});const r=await fetch('/api/attendance?'+q,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.code);setView(data);setSegments([...(data.candidate?.segments??data.suggestedSegments)]);setExcluded((data.candidate?.exclusions??[]).map((e:AttendanceReviewExclusion)=>e.eventId));setReason(data.candidate?.reason??data.proposal?.reason??'');}catch(e){setView(null);setMessage(errors[e instanceof Error?e.message:'']??'Chưa tải được bảng công. Kiểm tra nhân viên và tháng.');}finally{setBusy(false);}}
 async function act(action:'draft'|'approve'|'finalize'){
  if(!employee||!session||!view)return;setBusy(true);setMessage('');try{
   const selected=segments.filter(s=>!s.sourceEventIds.some(id=>excluded.includes(id))).map(s=>s.correction?{...s,correction:{source:'maker_proposal' as const,reason}}:s);
   const payload={action,employeeId,workplaceId:employee.workplaceId,month,expectedVersion:view.version,sourceHash:view.sourceHash,candidateHash:view.candidateHash,reason:action==='draft'?reason:approvalReason,segments:selected,exclusions:excluded.map(eventId=>({eventId,reason,classification:'unresolved'}))};
   const r=await fetch('/api/attendance',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify(payload)});const result=await r.json();if(!r.ok)throw Error(result.code);
   await load();setMessage(action==='draft'?'Đã lưu đề xuất. Chờ chủ doanh nghiệp kiểm tra.':action==='approve'?'Đã phê duyệt đề xuất.':'Đã chốt bảng công tháng.');
  }catch(e){setMessage(errors[e instanceof Error?e.message:'']??'Chưa lưu được thay đổi. Tải lại bảng công trước khi thử tiếp.');}finally{setBusy(false);}
 }
 function change(index:number,patch:Partial<AttendanceReviewSegment>){setSegments(current=>current.map((s,i)=>i===index?{...s,...patch,correction:{source:'maker_proposal',reason}}:s));}
 function toggle(id:string){const related=segments.find(s=>s.sourceEventIds.includes(id))?.sourceEventIds??[id];setExcluded(current=>current.includes(id)?current.filter(x=>!related.includes(x)):[...new Set([...current,...related])]);}
 function addCorrection(){if(!view)return;const used=new Set(segments.flatMap(s=>s.sourceEventIds));const raw=view.rawEvents.find(e=>e.insidePeriod&&!used.has(e.id)&&!excluded.includes(e.id));if(!raw){setMessage('Không còn chấm công gốc chưa gắn với khoảng thời gian.');return;}setSegments(current=>[...current,{id:crypto.randomUUID(),startUtcMs:raw.occurredAtUtcMs,endUtcMs:raw.occurredAtUtcMs+3600000,classification:'ordinary',sourceEventIds:[raw.id],scheduleRefs:[],correction:{source:'maker_proposal',reason}}]);}
 const maker=session?.actor.role==='accountant',frozen=!!view?.frozenSnapshot;
 return <main className={styles.shell}><header className={styles.header}><div><p className={styles.brand}>THE KAY’S GELATO</p><h1>Duyệt bảng công</h1><p>Kiểm tra chấm công, đề xuất điều chỉnh và chốt dữ liệu tháng.</p></div><Link href='/login'>Tài khoản</Link></header>
 {!loaded?<p role='status'>Đang kiểm tra phiên làm việc…</p>:!session?<section className={styles.card}><h2>Cần đăng nhập</h2><p>Bảng công chỉ dành cho tài khoản quản trị được xác thực.</p><Link href='/login'>Đăng nhập</Link></section>:<>
 <form className={styles.filters} onSubmit={e=>{e.preventDefault();setMessage('');void load();}}><label>Nhân viên<select aria-label='Nhân viên' value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setView(null);}}>{employees.map(e=><option key={e.id} value={e.id}>{e.displayName}</option>)}</select></label><label>Tháng<input type='month' value={month} onChange={e=>{setMonth(e.target.value);setView(null);}} required/></label><button disabled={busy||!employeeId} type='submit'>Xem bảng công</button><span className={styles.badge}>{maker?'Kế toán · lập đề xuất':'Chủ doanh nghiệp · phê duyệt'}</span></form>
 <p role='status' aria-live='polite' className={styles.notice}>{message}</p>
 {view&&<>
 {frozen?<section className={styles.success}><h2>Bảng công đã chốt</h2><p>Dữ liệu đã lưu bất biến. Thay đổi sau này cần quy trình điều chỉnh riêng.</p><p>Mã bảng công: {view.frozenSnapshot!.id}</p><code>{view.frozenSnapshot!.contentHash}</code></section>:<section className={styles.blockers}><h2>{view.blockers.length?`${view.blockers.length} mục cần xử lý`:view.decision?'Đề xuất đã được duyệt':view.proposal?'Đang chờ phê duyệt':'Bắt đầu kiểm tra bảng công'}</h2>{view.blockers.map((b,i)=><p key={i}><strong>{({MISSING_SCHEDULE:'Thiếu lịch có hiệu lực',RAW_EVENT_UNDISPOSED:'Chấm công chưa được xử lý',SOURCE_HASH_STALE:'Nguồn đã thay đổi',UNSUPPORTED_SCOPE:'Trường hợp cần làm rõ'} as Record<string,string>)[b.code]??'Cần kiểm tra'}</strong> · {b.code==='SOURCE_HASH_STALE'?'Lập đề xuất mới từ dữ liệu hiện tại.':b.code==='MISSING_SCHEDULE'?'Bổ sung lịch làm việc cho ngày liên quan trước khi duyệt.':b.code==='RAW_EVENT_UNDISPOSED'?'Gắn từng chấm công vào khoảng đề xuất hoặc loại trừ với lý do.':'Điều chỉnh hoặc loại trừ có lý do; giờ vừa thuộc ngày lễ vừa thuộc ban đêm cần quy tắc riêng.'}</p>)}<p>{maker?'Đối chiếu các mốc giờ bên dưới, ghi rõ lý do rồi gửi đề xuất.':'Đối chiếu đề xuất với nguồn gốc trước khi phê duyệt. Không phê duyệt khi dữ liệu còn thay đổi.'}</p></section>}
 <div className={styles.columns}><section className={styles.card}><h2>Chấm công gốc</h2><p className={styles.muted}>Giờ Việt Nam · dữ liệu gốc được giữ nguyên</p><div className={styles.tableWrap}><table><thead><tr><th>Thao tác</th><th>Thời điểm</th>{maker&&!frozen&&<th>Xử lý</th>}</tr></thead><tbody>{view.rawEvents.map(e=><tr key={e.id}><td>{e.direction==='IN'?'Vào ca':'Ra ca'}{!e.insidePeriod&&' (giáp tháng)'}</td><td>{time(e.occurredAtUtcMs)}</td>{maker&&!frozen&&<td>{e.insidePeriod&&<label className={styles.check}><input type='checkbox' checked={excluded.includes(e.id)} onChange={()=>toggle(e.id)}/>Loại khỏi thời gian trả lương</label>}</td>}</tr>)}</tbody></table></div>{!view.rawEvents.length&&<p>Chưa có dữ liệu chấm công trong kỳ.</p>}</section>
 <section className={styles.card}><h2>Lịch làm việc</h2><details><summary>{view.scheduledIntervals.length} khoảng thời gian theo lịch</summary>{view.scheduledIntervals.map((s,i)=><p key={i}>{time(s.startUtcMs)} → {time(s.endUtcMs)}</p>)}</details></section></div>
 <section className={styles.card}><h2>{frozen?'Khoảng thời gian đã chốt':maker?'Khoảng thời gian đề xuất':'Nội dung đề xuất cần duyệt'}</h2>{!maker&&view.proposal&&!view.candidate&&<p>Chưa tải đủ nội dung đề xuất. Không thể phê duyệt.</p>}
 {segments.map((s,i)=><fieldset key={s.id} className={styles.segment} disabled={!maker||frozen||excluded.some(id=>s.sourceEventIds.includes(id))}><legend>Khoảng {i+1} · {s.correction?'Có điều chỉnh':'Từ chấm công gốc'}</legend><label>Bắt đầu<input type='datetime-local' step='0.001' value={localInput(s.startUtcMs)} onChange={e=>{const at=fromLocal(e.target.value);if(Number.isFinite(at))change(i,{startUtcMs:at});}}/></label><label>Kết thúc<input type='datetime-local' step='0.001' value={localInput(s.endUtcMs)} onChange={e=>{const at=fromLocal(e.target.value);if(Number.isFinite(at))change(i,{endUtcMs:at});}}/></label><label>Phân loại<select value={s.classification} onChange={e=>change(i,{classification:e.target.value as AttendanceReviewSegment['classification']})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></fieldset>)}
 {maker&&!frozen&&<><button type='button' className={styles.secondary} onClick={addCorrection}>Thêm khoảng điều chỉnh</button><label>Lý do đề xuất<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder='Nguồn đối chiếu và lý do cho mọi thay đổi hoặc loại trừ' required/></label><p>{excluded.length} mốc chấm công được đề xuất loại trừ.</p><button disabled={busy||!view.canDraft||!reason.trim()} onClick={()=>void act('draft')}>Gửi đề xuất</button></>}
 {!maker&&view.proposal&&!frozen&&<><p><strong>Lý do của kế toán:</strong> {view.proposal.reason}</p><p>Đã đề xuất loại trừ {view.candidate?.exclusions.length??0} mốc chấm công.</p>{view.candidate?.exclusions.map(x=><p key={x.eventId}>Loại trừ · {time(view.rawEvents.find(e=>e.id===x.eventId)?.occurredAtUtcMs??0)} · {x.reason}</p>)}<label>Lý do phê duyệt<textarea value={approvalReason} maxLength={1000} onChange={e=>setApprovalReason(e.target.value)}/></label><div className={styles.actions}>{!view.decision&&<button disabled={busy||!view.canApprove||!view.candidate||!approvalReason.trim()} onClick={()=>void act('approve')}>Phê duyệt đề xuất</button>}{view.decision&&<button disabled={busy||!view.canFinalize||view.blockers.length>0} onClick={()=>void act('finalize')}>Chốt bảng công tháng</button>}<Link href='/login/totp'>Xác thực lại</Link></div></>}
 </section></>}
 </>}
 </main>;
}
