import { expect, test } from 'vitest';
import { canonicalReview, normalizeReviewCandidate, reviewPeriod, suggestedReviewSegments, validateReviewCandidate, type ReviewCandidate, type ReviewSource } from '../src/review';

const start=Date.parse('2026-01-06T08:00:00.000Z');
function source(events:ReviewSource['rawEvents'], intervals:ReviewSource['scheduledIntervals']=[{startUtcMs:start,endUtcMs:start+3_600_000,scheduleRef:'schedule-a'}], holidays:readonly string[]=[]):ReviewSource{return {rawEvents:events,scheduledIntervals:intervals,holidayLocalDates:holidays};}
function event(id:string,direction:'IN'|'OUT',occurredAtUtcMs:number,insidePeriod=true){return {id,direction,occurredAtUtcMs,insidePeriod};}
function segment(id:string,from:number,to:number,sourceEventIds:readonly string[],classification:'ordinary'|'holiday_daytime'|'out_of_schedule'|'night_work'='ordinary',correction?:{source:'maker_proposal';reason:string}){return {id,startUtcMs:from,endUtcMs:to,classification,sourceEventIds,scheduleRefs:['schedule-a'],...(correction?{correction}:{})};}
function candidate(segments:ReviewCandidate['segments'],exclusions:ReviewCandidate['exclusions']=[]):ReviewCandidate{return {reason:'synthetic review',segments,exclusions};}

test('shop month uses Asia/Ho_Chi_Minh boundaries',()=>expect(reviewPeriod('2026-01').start.toISOString()).toBe('2025-12-31T17:00:00.000Z'));
test('preserves exact 59/60/61-second payable durations',()=>{for(const seconds of [59,60,61]){const end=start+seconds*1000;const value=validateReviewCandidate('2026-01',source([event('in','IN',start),event('out','OUT',end)]),candidate([segment('pair',start,end,['in','out'])]));expect(value.totalPayableDurationMs).toBe(String(seconds*1000));}});
test('allows a reasoned corrected missing punch and a complete exclusion to resolve raw anomalies',()=>{const missing=source([event('in','IN',start)]);expect(validateReviewCandidate('2026-01',missing,candidate([segment('corrected',start,start+60_000,['in'],'ordinary',{source:'maker_proposal',reason:'Recorded camera evidence'})])).blockers).toEqual([]);const duplicate=source([event('in-a','IN',start),event('in-b','IN',start+1_000)]);expect(validateReviewCandidate('2026-01',duplicate,candidate([],[{eventId:'in-a',reason:'duplicate kiosk retry',classification:'unresolved'},{eventId:'in-b',reason:'duplicate kiosk retry',classification:'unresolved'}])).blockers).toEqual([]);});
test('rejects holiday downgrade, changed normal boundaries, duplicate disposition and outside-month time',()=>{const holiday=source([event('in','IN',start),event('out','OUT',start+60_000)],undefined,['2026-01-06']);expect(()=>validateReviewCandidate('2026-01',holiday,candidate([segment('ordinary',start,start+60_000,['in','out'])]))).toThrow('CLASSIFICATION_EVIDENCE_MISMATCH');const ordinary=source([event('in','IN',start),event('out','OUT',start+60_000)]);expect(()=>validateReviewCandidate('2026-01',ordinary,candidate([segment('changed',start+1,start+60_000,['in','out'])]))).toThrow('CORRECTION_REQUIRED');expect(()=>validateReviewCandidate('2026-01',ordinary,candidate([segment('one',start,start+60_000,['in','out']),segment('two',start+60_000,start+61_000,['in'],'ordinary',{source:'maker_proposal',reason:'duplicate source'})]))).toThrow('RAW_EVENT_DISPOSITION_INVALID');const period=reviewPeriod('2026-01');expect(()=>validateReviewCandidate('2026-01',ordinary,candidate([segment('outside',period.startUtcMs-1,period.startUtcMs+1,['in','out'])]))).toThrow('SEGMENT_OUTSIDE_PERIOD');});
test('requires both cross-month source IDs and canonicalizes stable reversed input',()=>{const period=reviewPeriod('2026-01'),raw=source([event('prior-in','IN',period.startUtcMs-60_000,false),event('out','OUT',period.startUtcMs+60_000,true)],[{startUtcMs:period.startUtcMs,endUtcMs:period.startUtcMs+60_000,scheduleRef:'schedule-a'}]);expect(validateReviewCandidate('2026-01',raw,candidate([segment('cross',period.startUtcMs,period.startUtcMs+60_000,['prior-in','out'],'night_work')])).blockers).toEqual([]);expect(validateReviewCandidate('2026-01',raw,candidate([],[{eventId:'out',reason:'only one',classification:'unresolved'}])).blockers.map(x=>x.code)).toContain('RAW_EVENT_UNDISPOSED');const normalized=normalizeReviewCandidate({reason:'  ordered  ',segments:[segment('z',start+60_000,start+61_000,['out','in']),segment('a',start,start+60_000,['in','out'])],exclusions:[]});expect(normalized.reason).toBe('ordered');expect(normalized.segments.map(value=>value.id)).toEqual(['a','z']);expect(normalized.segments[0]!.sourceEventIds).toEqual(['in','out']);});
test('does not silently suggest ordinary holiday or night time and rejects malformed runtime values',()=>{const holiday=source([event('in','IN',start),event('out','OUT',start+60_000)],undefined,['2026-01-06']);expect(suggestedReviewSegments('2026-01',holiday)[0]!.classification).toBe('holiday_daytime');const night=source([event('in','IN',Date.parse('2026-01-06T16:00:00.000Z')),event('out','OUT',Date.parse('2026-01-06T16:01:00.000Z'))]);expect(suggestedReviewSegments('2026-01',night)[0]!.classification).toBe('night_work');expect(()=>normalizeReviewCandidate({reason:'x',segments:[{...segment('bad',start,start+1,['in','in']),classification:'invalid'}] as never,exclusions:[]})).toThrow('REVIEW_CANDIDATE_INVALID');expect(()=>canonicalReview({value:undefined})).toThrow('CANONICAL_VALUE_INVALID');expect(()=>canonicalReview(Number.NaN)).toThrow('CANONICAL_VALUE_INVALID');});

test('canonical writer rejects cyclic arrays instead of recursing indefinitely',()=>{const cycle:unknown[]=[];cycle.push(cycle);expect(()=>canonicalReview(cycle)).toThrow('CANONICAL_VALUE_INVALID');});
test('explicit outside-schedule work can be reviewed when its date has effective schedule evidence',()=>{const raw=source([event('in','IN',start),event('out','OUT',start+60_000)],[]);const known={...raw,missingScheduleLocalDates:[]};expect(validateReviewCandidate('2026-01',known,candidate([{...segment('extra',start,start+60_000,['in','out'],'out_of_schedule'),scheduleRefs:[]}])).blockers).toEqual([]);});
