import { createHash, randomBytes, randomUUID } from 'node:crypto';
import argon2 from 'argon2';
import type { Pool, PoolClient } from 'pg';
import { AuthRepository } from './auth';
import { authorize, type UserActor } from '../../auth/authorization';
import { hashSecret, validCsrf } from '../../auth/csrf';
import type { WindowsSecretProtector } from '../../secrets/windows-dpapi';
import { withTransaction } from '../transaction';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
type Credentials={sessionToken:string;csrfToken:string};
export class KioskAdminRepository {
 private readonly auth:AuthRepository;
 constructor(private readonly pool:Pool,protector:WindowsSecretProtector,private readonly organizationId:string,private readonly now=()=>new Date()){this.auth=new AuthRepository(pool,protector,{organizationId,now});}
 private async owner(tx:PoolClient,c:Credentials):Promise<UserActor>{const actor=await this.auth.checkCsrf(c.sessionToken,c.csrfToken);const row=(await tx.query<{role:'owner'|'accountant';active:boolean;mfa_satisfied_at:Date|null;expires_at:Date;revoked_at:Date|null;csrf_hash:string|null}>('SELECT u.role,u.active,s.mfa_satisfied_at,s.expires_at,s.revoked_at,s.csrf_hash FROM users u JOIN sessions s ON s.user_id=u.id AND s.organization_id=u.organization_id WHERE u.id=$1 AND u.organization_id=$2 AND s.id=$3 AND s.token_hash=$4 FOR UPDATE',[actor.userId,this.organizationId,actor.sessionId,hashSecret(c.sessionToken)])).rows[0];if(!row?.active||row.revoked_at||row.expires_at<=this.now()||!row.mfa_satisfied_at||!validCsrf(row.csrf_hash??'',c.csrfToken))throw Error('UNAUTHENTICATED');const trusted={...actor,role:row.role,mfaSatisfiedAt:row.mfa_satisfied_at} as UserActor;authorize(trusted,'ATTENDANCE_APPROVE',this.now(),{organizationId:this.organizationId});return trusted;}
 async enroll(c:Credentials,input:{workplaceId:string;expiresAt:Date}){if(!(input.expiresAt instanceof Date)||input.expiresAt.getTime()<=this.now().getTime()+60_000)throw Error('INVALID_DEVICE_EXPIRY');const secret=randomBytes(32).toString('base64url'),id=randomUUID(),sessionId=randomUUID();await withTransaction(this.pool,async tx=>{const actor=await this.owner(tx,c);if(!(await tx.query('SELECT id FROM workplaces WHERE id=$1 AND organization_id=$2',[input.workplaceId,this.organizationId])).rowCount)throw Error('WORKPLACE_NOT_FOUND');await tx.query('INSERT INTO kiosk_devices(id,organization_id,workplace_id,session_id,token_hash,enrolled_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,this.organizationId,input.workplaceId,sessionId,hash(secret),this.now(),input.expiresAt]);await tx.query("INSERT INTO audit_events(id,organization_id,actor_id,action,aggregate_id,created_at) VALUES($1,$2,$3,'kiosk.device.enrolled',$4,$5)",[randomUUID(),this.organizationId,actor.userId,id,this.now()]);});return {deviceId:id,sessionId,token:secret};}
 async rotate(c:Credentials,deviceId:string,expiresAt:Date){if(expiresAt.getTime()<=this.now().getTime()+60_000)throw Error('INVALID_DEVICE_EXPIRY');const secret=randomBytes(32).toString('base64url');await withTransaction(this.pool,async tx=>{const actor=await this.owner(tx,c);await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[deviceId]);const q=await tx.query('UPDATE kiosk_devices SET session_id=$3,token_hash=$4,expires_at=$5,revoked_at=NULL WHERE id=$1 AND organization_id=$2',[deviceId,this.organizationId,randomUUID(),hash(secret),expiresAt]);if(!q.rowCount)throw Error('DEVICE_NOT_FOUND');await tx.query("INSERT INTO audit_events(id,organization_id,actor_id,action,aggregate_id,created_at) VALUES($1,$2,$3,'kiosk.device.rotated',$4,$5)",[randomUUID(),this.organizationId,actor.userId,deviceId,this.now()]);});return {token:secret};}
 async revoke(c:Credentials,deviceId:string){await withTransaction(this.pool,async tx=>{const actor=await this.owner(tx,c);await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[deviceId]);const q=await tx.query('UPDATE kiosk_devices SET revoked_at=$3 WHERE id=$1 AND organization_id=$2 AND revoked_at IS NULL',[deviceId,this.organizationId,this.now()]);if(!q.rowCount)throw Error('DEVICE_NOT_FOUND');await tx.query("INSERT INTO audit_events(id,organization_id,actor_id,action,aggregate_id,created_at) VALUES($1,$2,$3,'kiosk.device.revoked',$4,$5)",[randomUUID(),this.organizationId,actor.userId,deviceId,this.now()]);});}
 async setEmployeePin(c:Credentials,input:{employeeId:string;deviceId:string;employeeCode:string;pin:string}){if(!/^\d{6}$/.test(input.pin)||!/^[A-Za-z0-9_-]{1,64}$/.test(input.employeeCode))throw Error('INVALID_KIOSK_PIN');const pinHash=await argon2.hash(input.pin,{type:argon2.argon2id});await withTransaction(this.pool,async tx=>{const actor=await this.owner(tx,c);const device=(await tx.query<{workplace_id:string}>('SELECT workplace_id FROM kiosk_devices WHERE id=$1 AND organization_id=$2 AND revoked_at IS NULL',[input.deviceId,this.organizationId])).rows[0];const employee=(await tx.query<{workplace_id:string}>('SELECT workplace_id FROM employees WHERE id=$1 AND organization_id=$2 AND status=\'active\'',[input.employeeId,this.organizationId])).rows[0];if(!device||!employee||device.workplace_id!==employee.workplace_id)throw Error('KIOSK_EMPLOYEE_BINDING_INVALID');await tx.query('INSERT INTO kiosk_employee_pins(employee_id,organization_id,device_id,employee_code,pin_hash) VALUES($1,$2,$3,$4,$5) ON CONFLICT(employee_id,device_id) DO UPDATE SET employee_code=EXCLUDED.employee_code,pin_hash=EXCLUDED.pin_hash,revoked_at=NULL',[input.employeeId,this.organizationId,input.deviceId,input.employeeCode,pinHash]);await tx.query('INSERT INTO kiosk_employee_states(employee_id,organization_id,workplace_id,last_direction,updated_at) VALUES($1,$2,$3,NULL,$4) ON CONFLICT(employee_id) DO NOTHING',[input.employeeId,this.organizationId,employee.workplace_id,this.now()]);await tx.query("INSERT INTO audit_events(id,organization_id,actor_id,action,aggregate_id,created_at) VALUES($1,$2,$3,'kiosk.pin.set',$4,$5)",[randomUUID(),this.organizationId,actor.userId,input.employeeId,this.now()]);});}
}
