import { createHash } from 'node:crypto';
import { afterAll, expect, test, vi } from 'vitest';
import { reviewFixture, reviewPool } from './review-support';
const pool=reviewPool();afterAll(()=>pool.end());
type Fixture=Awaited<ReturnType<typeof reviewFixture>>;
const scope=(s:Fixture)=>({employeeId:s.employeeId,workplaceId:s.workplaceId,month:'2026-01' as const});
const maker=(s:Fixture)=>({sessionToken:s.accountantSession.token,csrfToken:s.accountantSession.csrfToken});
const checker=(s:Fixture)=>({sessionToken:s.ownerSession.token,csrfToken:s.ownerSession.csrfToken});
async function proposed(s:Fixture){const view=await s.accountantRepo.list(s.accountantSession.token,scope(s));return s.accountantRepo.draft(maker(s),{...scope(s),expectedVersion:view.version,sourceHash:view.sourceHash,segments:view.suggestedSegments,exclusions:[],reason:'Verified synthetic raw records and schedule'});}
async function approved(s:Fixture){const draft=await proposed(s),decision=await s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:draft.version,candidateHash:draft.candidateHash,reason:'Independent synthetic review'});return {...scope(s),expectedVersion:decision.version,candidateHash:draft.candidateHash};}
test('actual intervals freeze exact milliseconds with separate maker/checker and concurrent idempotency',async()=>{
 const s=await reviewFixture(pool),draft=await proposed(s);await expect(s.accountantRepo.approve(maker(s),{...scope(s),expectedVersion:draft.version,candidateHash:draft.candidateHash,reason:'No authority'})).rejects.toThrow('FORBIDDEN');
 const view=await s.ownerRepo.list(s.ownerSession.token,scope(s));expect(view.candidate?.segments).toHaveLength(1);expect(view.blockers).toEqual([]);
 const decision=await s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:draft.version,candidateHash:draft.candidateHash,reason:'Independent review'}),input={...scope(s),expectedVersion:decision.version,candidateHash:draft.candidateHash};
 const [one,two]=await Promise.all([s.ownerRepo.finalize(checker(s),input),s.ownerRepo.finalize(checker(s),input)]);expect(one.snapshot.id).toBe(two.snapshot.id);expect([one.replayed,two.replayed].filter(Boolean)).toHaveLength(1);
 const payload=JSON.parse(one.snapshot.canonicalPayload);expect(payload.totalPayableDurationMs).toBe('3600061');expect(payload.segments[0].durationMs).toBe('3600061');expect(payload.source.rawEvents).toHaveLength(2);expect(payload.source.scheduleEvidence).toHaveLength(32);expect(payload.proposal.madeBy).not.toBe(payload.decision.approvedBy);expect(payload.approvedAtUtcMs).toBe(s.owner.clock.value);expect(createHash('sha256').update(one.snapshot.canonicalPayload).digest('hex')).toBe(one.snapshot.contentHash);
 await expect(pool.query("UPDATE attendance_snapshots SET status='x' WHERE id=$1",[one.snapshot.id])).rejects.toMatchObject({code:'42501'});
 await expect(pool.query('DELETE FROM attendance_review_proposals WHERE id=$1',[draft.proposal.id])).rejects.toMatchObject({code:'55000'});
});
test('CSRF, fresh MFA, tenant and current role are enforced by write services',async()=>{const s=await reviewFixture(pool),view=await s.accountantRepo.list(s.accountantSession.token,scope(s));await expect(s.accountantRepo.draft({...maker(s),csrfToken:'bad'},{...scope(s),expectedVersion:view.version,sourceHash:view.sourceHash,segments:view.suggestedSegments,exclusions:[],reason:'bad csrf'})).rejects.toThrow('CSRF');const d=await proposed(s);await pool.query('UPDATE sessions SET mfa_satisfied_at=$2 WHERE id=$1',[s.ownerSession.actor.sessionId,new Date(s.owner.clock.value-660000)]);await expect(s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:d.version,candidateHash:d.candidateHash,reason:'stale'})).rejects.toThrow('FRESH_TOTP_REQUIRED');const other=await reviewFixture(pool);await expect(s.ownerRepo.list(other.ownerSession.token,scope(s))).rejects.toThrow();});
test('appended raw evidence invalidates approval before finalization',async()=>{const s=await reviewFixture(pool),input=await approved(s);await s.raw('IN','2026-01-07T01:00:00Z');await expect(s.ownerRepo.finalize(checker(s),input)).rejects.toThrow('SOURCE_HASH_STALE');const view=await s.ownerRepo.list(s.ownerSession.token,scope(s));expect(view.canFinalize).toBe(false);expect(view.blockers.map(b=>b.code)).toContain('SOURCE_HASH_STALE');expect((await pool.query('SELECT id FROM attendance_snapshots WHERE employee_id=$1',[s.employeeId])).rowCount).toBe(0);});
test('a new proposal invalidates prior decision and version',async()=>{const s=await reviewFixture(pool),old=await approved(s),next=await proposed(s);await expect(s.ownerRepo.finalize(checker(s),old)).rejects.toThrow('STALE_VERSION');await expect(s.ownerRepo.finalize(checker(s),{...old,expectedVersion:next.version,candidateHash:next.candidateHash})).rejects.toThrow('APPROVAL_REQUIRED');});
test('complete exclusions retain raw evidence and contribute no payable duration',async()=>{const s=await reviewFixture(pool),view=await s.accountantRepo.list(s.accountantSession.token,scope(s));const draft=await s.accountantRepo.draft(maker(s),{...scope(s),expectedVersion:0,sourceHash:view.sourceHash,segments:[],exclusions:view.rawEvents.map(e=>({eventId:e.id,reason:'Rejected synthetic duplicate shift',classification:'ordinary' as const})),reason:'Explicit exclusion review'});const d=await s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:draft.version,candidateHash:draft.candidateHash,reason:'Reviewed exclusions'});const final=await s.ownerRepo.finalize(checker(s),{...scope(s),expectedVersion:d.version,candidateHash:draft.candidateHash});const payload=JSON.parse(final.snapshot.canonicalPayload);expect(payload.totalPayableDurationMs).toBe('0');expect(payload.exclusions).toHaveLength(2);expect(payload.source.rawEvents).toHaveLength(2);});
test('missing punch requires explicit correction or exclusion before approval',async()=>{const s=await reviewFixture(pool),id=await s.raw('IN','2026-01-07T01:00:00Z'),view=await s.accountantRepo.list(s.accountantSession.token,scope(s));const blocked=await proposed(s);await expect(s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:blocked.version,candidateHash:blocked.candidateHash,reason:'Incomplete'})).rejects.toThrow('REVIEW_BLOCKED');const draft=await s.accountantRepo.draft(maker(s),{...scope(s),expectedVersion:blocked.version,sourceHash:view.sourceHash,segments:[...view.suggestedSegments,{id:'correction',startUtcMs:Date.parse('2026-01-07T01:00:00Z'),endUtcMs:Date.parse('2026-01-07T02:00:00Z'),classification:'ordinary',sourceEventIds:[id],scheduleRefs:[],correction:{source:'maker_proposal',reason:'Synthetic missing OUT witness'}}],exclusions:[],reason:'Reasoned missing punch correction'});await expect(s.ownerRepo.approve(checker(s),{...scope(s),expectedVersion:draft.version,candidateHash:draft.candidateHash,reason:'Checked correction provenance'})).resolves.toHaveProperty('version');});
test('snapshot and review audit roll back together when the audit insert fails',async()=>{const s=await reviewFixture(pool),input=await approved(s);const original=pool.connect.bind(pool);const spy=vi.spyOn(pool,'connect').mockImplementation(((callback?:unknown)=>{if(callback)return original(callback as never);return (async()=>{const client=await original();const query=client.query.bind(client);client.query=((...args:unknown[])=>{if(typeof args[0]==='string'&&args[0].startsWith('INSERT INTO attendance_review_audits'))return Promise.reject(Error('synthetic audit failure'));return (query as (...a:unknown[])=>unknown)(...args);}) as typeof client.query;const release=client.release.bind(client);client.release=()=>{client.query=query;release();};return client;})();}) as typeof pool.connect);try{await expect(s.ownerRepo.finalize(checker(s),input)).rejects.toThrow('synthetic audit failure');}finally{spy.mockRestore();}expect((await pool.query('SELECT id FROM attendance_snapshots WHERE employee_id=$1',[s.employeeId])).rowCount).toBe(0);await expect(s.ownerRepo.finalize(checker(s),input)).resolves.toHaveProperty('replayed',false);});


test('a frozen review keeps its own source when new raw records arrive later',async()=>{const s=await reviewFixture(pool),input=await approved(s),final=await s.ownerRepo.finalize(checker(s),input);await s.raw('IN','2026-01-08T01:00:00Z');const view=await s.ownerRepo.list(s.ownerSession.token,scope(s));expect(view.frozenSnapshot?.contentHash).toBe(final.snapshot.contentHash);expect(view.rawEvents).toHaveLength(2);expect(view.blockers).toEqual([]);expect(view.canDraft||view.canApprove||view.canFinalize).toBe(false);});
