import { createHash } from 'node:crypto';
import { assertSafeUtcMilliseconds } from './state-machine';
import type { AttendanceReviewBlocker, AttendanceReviewExclusion, AttendanceReviewInterval, AttendanceReviewRawEvent, AttendanceReviewSegment } from '../../contracts/src/attendance-review';

export const ATTENDANCE_REVIEW_CANONICALIZATION_VERSION = 'attendance-review/v1';
const HCM_OFFSET_MS = 7 * 60 * 60 * 1000;
const MONTH = /^(\d{4})-(\d{2})$/;
type Classification = AttendanceReviewSegment['classification'];
export interface ReviewSource {
 readonly rawEvents: readonly AttendanceReviewRawEvent[];
 readonly scheduledIntervals: readonly AttendanceReviewInterval[];
 readonly holidayLocalDates: readonly string[];
 readonly scheduleEvidence?: unknown;
 readonly missingScheduleLocalDates?: readonly string[];
}
export interface ReviewCandidate { readonly segments: readonly AttendanceReviewSegment[]; readonly exclusions: readonly AttendanceReviewExclusion[]; readonly reason: string; }
function fail(code:string):never { throw Object.assign(new Error(code),{code}); }
function text(value:unknown, code='REVIEW_CANDIDATE_INVALID', max=1_000):string { if(typeof value!=='string') fail(code); const trimmed=value.trim(); if(!trimmed||trimmed.length>max) fail(code); return trimmed; }
function safeMs(value:unknown, code='REVIEW_CANDIDATE_INVALID'):number { if(typeof value!=='number'||!Number.isSafeInteger(value)) fail(code); assertSafeUtcMilliseconds(value); return value; }
function localDate(ms:number):string { return new Date(ms+HCM_OFFSET_MS).toISOString().slice(0,10); }
function localDayStartUtc(date:string):number { return Date.parse(`${date}T00:00:00.000Z`)-HCM_OFFSET_MS; }
function uniqueStrings(value:unknown, code='REVIEW_CANDIDATE_INVALID'):readonly string[] { if(!Array.isArray(value)) fail(code); const values=value.map(item=>text(item,code,200)); if(new Set(values).size!==values.length) fail(code); return Object.freeze(values.sort()); }

export function reviewPeriod(month:string):{startUtcMs:number;endUtcMs:number;start:Date;end:Date}{const matched=MONTH.exec(month);if(!matched)fail('REVIEW_MONTH_INVALID');const year=Number(matched[1]),index=Number(matched[2]);if(index<1||index>12)fail('REVIEW_MONTH_INVALID');const startUtcMs=Date.UTC(year,index-1,1)-HCM_OFFSET_MS,endUtcMs=Date.UTC(year,index,1)-HCM_OFFSET_MS;return {startUtcMs,endUtcMs,start:new Date(startUtcMs),end:new Date(endUtcMs)};}
export function canonicalReview(value:unknown):string { const seen=new Set<object>(); const visit=(current:unknown):string=>{if(current===null)return 'null';if(typeof current==='string'||typeof current==='boolean')return JSON.stringify(current);if(typeof current==='number'){if(!Number.isFinite(current))fail('CANONICAL_VALUE_INVALID');return JSON.stringify(current);}if(Array.isArray(current)){if(seen.has(current))fail('CANONICAL_VALUE_INVALID');seen.add(current);const result='['+current.map(visit).join(',')+']';seen.delete(current);return result;}if(typeof current!=='object')fail('CANONICAL_VALUE_INVALID');if(seen.has(current))fail('CANONICAL_VALUE_INVALID');seen.add(current);const record=current as Record<string,unknown>;const result=`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${visit(record[key])}`).join(',')}}`;seen.delete(current);return result;};return visit(value); }
export function hashReview(value:unknown):string{return createHash('sha256').update(canonicalReview(value),'utf8').digest('hex');}

export function normalizeReviewCandidate(candidate:ReviewCandidate):ReviewCandidate {
 if(!candidate||typeof candidate!=='object'||!Array.isArray(candidate.segments)||!Array.isArray(candidate.exclusions))fail('REVIEW_CANDIDATE_INVALID');
 const segments=candidate.segments.map(raw=>{if(!raw||typeof raw!=='object')fail('REVIEW_CANDIDATE_INVALID');const value=raw as AttendanceReviewSegment;const id=text(value.id,'REVIEW_CANDIDATE_INVALID',200),startUtcMs=safeMs(value.startUtcMs),endUtcMs=safeMs(value.endUtcMs);if(endUtcMs<=startUtcMs)fail('REVIEW_CANDIDATE_INVALID');if(!['ordinary','holiday_daytime','out_of_schedule','night_work'].includes(value.classification))fail('REVIEW_CANDIDATE_INVALID');const correction=value.correction===undefined?undefined:(()=>{const item=value.correction as {source?:unknown;reason?:unknown};if(item?.source!=='maker_proposal')fail('REVIEW_CANDIDATE_INVALID');return Object.freeze({source:'maker_proposal' as const,reason:text(item.reason,'REVIEW_CANDIDATE_INVALID')});})();return Object.freeze({id,startUtcMs,endUtcMs,classification:value.classification,sourceEventIds:uniqueStrings(value.sourceEventIds),scheduleRefs:uniqueStrings(value.scheduleRefs),...(correction?{correction}:{})});});
 if(new Set(segments.map(value=>value.id)).size!==segments.length)fail('REVIEW_CANDIDATE_INVALID');
 const exclusions=candidate.exclusions.map(raw=>{if(!raw||typeof raw!=='object')fail('REVIEW_CANDIDATE_INVALID');const value=raw as AttendanceReviewExclusion;if(!['ordinary','holiday_daytime','out_of_schedule','night_work','unresolved'].includes(value.classification))fail('REVIEW_CANDIDATE_INVALID');return Object.freeze({eventId:text(value.eventId,'REVIEW_CANDIDATE_INVALID',200),reason:text(value.reason,'REVIEW_CANDIDATE_INVALID'),classification:value.classification});});
 if(new Set(exclusions.map(value=>value.eventId)).size!==exclusions.length)fail('REVIEW_CANDIDATE_INVALID');
 return Object.freeze({reason:text(candidate.reason,'REVIEW_CANDIDATE_INVALID'),segments:Object.freeze(segments.sort((a,b)=>a.startUtcMs-b.startUtcMs||a.endUtcMs-b.endUtcMs||a.id.localeCompare(b.id))),exclusions:Object.freeze(exclusions.sort((a,b)=>a.eventId.localeCompare(b.eventId)))});
}

type Pair={readonly input:AttendanceReviewRawEvent;readonly output:AttendanceReviewRawEvent;readonly startUtcMs:number;readonly endUtcMs:number;readonly anomalyFree:boolean};
function pairs(events:readonly AttendanceReviewRawEvent[]):{pairs:readonly Pair[];anomalyIds:ReadonlySet<string>}{const result:Pair[]=[];const bad=new Set<string>();let open:AttendanceReviewRawEvent|undefined;let previous=-Infinity;for(const current of events){safeMs(current.occurredAtUtcMs,'SOURCE_INVALID');text(current.id,'SOURCE_INVALID',200);if(current.occurredAtUtcMs<previous)bad.add(current.id);previous=current.occurredAtUtcMs;if(current.direction==='IN'){if(open){bad.add(open.id);bad.add(current.id);}open=current;continue;}if(current.direction!=='OUT'){fail('SOURCE_INVALID');}if(!open){bad.add(current.id);continue;}if(current.occurredAtUtcMs<=open.occurredAtUtcMs){bad.add(open.id);bad.add(current.id);open=undefined;continue;}result.push({input:open,output:current,startUtcMs:open.occurredAtUtcMs,endUtcMs:current.occurredAtUtcMs,anomalyFree:!bad.has(open.id)&&!bad.has(current.id)});open=undefined;}if(open)bad.add(open.id);return {pairs:Object.freeze(result),anomalyIds:bad};}
function contained(interval:{startUtcMs:number;endUtcMs:number}, schedules:readonly AttendanceReviewInterval[]):boolean { let cursor=interval.startUtcMs;for(const schedule of [...schedules].sort((a,b)=>a.startUtcMs-b.startUtcMs)){if(schedule.startUtcMs>cursor)break;if(schedule.endUtcMs>cursor)cursor=schedule.endUtcMs;if(cursor>=interval.endUtcMs)return true;}return false; }
function intersectsNight(interval:{startUtcMs:number;endUtcMs:number}):boolean { for(let day=localDayStartUtc(localDate(interval.startUtcMs));day<interval.endUtcMs;day+=86_400_000){if(interval.startUtcMs<day+6*3_600_000&&interval.endUtcMs>day)return true;if(interval.startUtcMs<day+86_400_000&&interval.endUtcMs>day+22*3_600_000)return true;}return false; }
function intersectsHoliday(interval:{startUtcMs:number;endUtcMs:number}, holidays:readonly string[]):boolean { const known=new Set(holidays);for(let day=localDayStartUtc(localDate(interval.startUtcMs));day<interval.endUtcMs;day+=86_400_000)if(known.has(localDate(day)))return true;return false; }
function evidence(interval:{startUtcMs:number;endUtcMs:number},source:ReviewSource):Classification|'unsupported' { const night=intersectsNight(interval),holiday=intersectsHoliday(interval,source.holidayLocalDates);if(night&&holiday)return 'unsupported';if(night)return 'night_work';if(holiday)return 'holiday_daytime';if(!contained(interval,source.scheduledIntervals))return 'out_of_schedule';return 'ordinary'; }
function refsFor(interval:{startUtcMs:number;endUtcMs:number},source:ReviewSource):readonly string[]{return Object.freeze(source.scheduledIntervals.filter(value=>value.startUtcMs<interval.endUtcMs&&value.endUtcMs>interval.startUtcMs).map(value=>value.scheduleRef).sort());}
function blocker(code:AttendanceReviewBlocker['code'],eventIds:readonly string[],message:string,nextAction:string):AttendanceReviewBlocker{return {code,eventIds:Object.freeze([...eventIds].sort()),message,nextAction};}

export function validateReviewCandidate(month:string,source:ReviewSource,candidate:ReviewCandidate):{candidateHash:string;blockers:readonly AttendanceReviewBlocker[];totalPayableDurationMs:string}{const period=reviewPeriod(month),normalized=normalizeReviewCandidate(candidate),allIds=new Set(source.rawEvents.map(value=>value.id));if(allIds.size!==source.rawEvents.length)fail('SOURCE_INVALID');const {pairs:rawPairs,anomalyIds}=pairs(source.rawEvents),disposed=new Map<string,'segment'|'correction'|'exclusion'>();let priorEnd=period.startUtcMs,total=0n;const blockers:AttendanceReviewBlocker[]=[];
 for(const segment of normalized.segments){if(segment.startUtcMs<period.startUtcMs||segment.endUtcMs>period.endUtcMs)fail('SEGMENT_OUTSIDE_PERIOD');if(segment.startUtcMs<priorEnd)fail('SEGMENT_OVERLAP');priorEnd=segment.endUtcMs;if(!segment.sourceEventIds.length)fail('SEGMENT_SOURCE_REQUIRED');for(const id of segment.sourceEventIds){if(!allIds.has(id)||disposed.has(id))fail('RAW_EVENT_DISPOSITION_INVALID');disposed.set(id,segment.correction?'correction':'segment');}const classification=evidence(segment,source);if(classification==='unsupported'){blockers.push(blocker('UNSUPPORTED_SCOPE',segment.sourceEventIds,'Holiday and night evidence cannot be represented by the current classification contract.','Escalate this interval for a supported classification.'));}else if(segment.classification!==classification)fail('CLASSIFICATION_EVIDENCE_MISMATCH');if(!segment.correction){const exact=rawPairs.find(pair=>pair.anomalyFree&&segment.sourceEventIds.length===2&&segment.sourceEventIds.includes(pair.input.id)&&segment.sourceEventIds.includes(pair.output.id)&&Math.max(pair.startUtcMs,period.startUtcMs)===segment.startUtcMs&&Math.min(pair.endUtcMs,period.endUtcMs)===segment.endUtcMs);if(!exact)fail('CORRECTION_REQUIRED');}if(source.missingScheduleLocalDates===undefined&&!contained(segment,source.scheduledIntervals))blockers.push(blocker('MISSING_SCHEDULE',segment.sourceEventIds,'A payable segment lacks complete effective schedule evidence.','Assign or correct the schedule before approval.'));total+=BigInt(segment.endUtcMs)-BigInt(segment.startUtcMs);}
 for(const exclusion of normalized.exclusions){if(!allIds.has(exclusion.eventId)||disposed.has(exclusion.eventId))fail('RAW_EVENT_DISPOSITION_INVALID');disposed.set(exclusion.eventId,'exclusion');}
 const undisposed=[...allIds].filter(id=>!disposed.has(id));if(undisposed.length)blockers.push(blocker('RAW_EVENT_UNDISPOSED',undisposed,'Every loaded source event needs a segment or reasoned exclusion.','Classify or exclude every source event.'));
 const unresolvedAnomalies=[...anomalyIds].filter(id=>disposed.get(id)!=='correction'&&disposed.get(id)!=='exclusion');if(unresolvedAnomalies.length)blockers.push(blocker('UNSUPPORTED_SCOPE',unresolvedAnomalies,'Raw attendance anomalies require a reasoned correction or explicit exclusion.','Correct or exclude each affected event.'));
 if(source.missingScheduleLocalDates?.some(date=>normalized.segments.some(segment=>segment.startUtcMs<localDayStartUtc(date)+86_400_000&&segment.endUtcMs>localDayStartUtc(date))))blockers.push(blocker('MISSING_SCHEDULE',[],`Missing schedule evidence for ${[...source.missingScheduleLocalDates].sort().join(', ')}. `,'Resolve missing schedule evidence before approval.'));
 const payload={canonicalizationVersion:ATTENDANCE_REVIEW_CANONICALIZATION_VERSION,month,sourceHash:hashReview(source),segments:normalized.segments,exclusions:normalized.exclusions,reason:normalized.reason};return {candidateHash:hashReview(payload),blockers:Object.freeze(blockers),totalPayableDurationMs:total.toString()};}
export function suggestedReviewSegments(month:string,source:ReviewSource):readonly AttendanceReviewSegment[]{const period=reviewPeriod(month),{pairs:rawPairs}=pairs(source.rawEvents),result:AttendanceReviewSegment[]=[];for(const pair of rawPairs){if(!pair.anomalyFree)continue;const startUtcMs=Math.max(pair.startUtcMs,period.startUtcMs),endUtcMs=Math.min(pair.endUtcMs,period.endUtcMs);if(endUtcMs<=startUtcMs)continue;const interval={startUtcMs,endUtcMs},classification=evidence(interval,source);if(classification==='unsupported')continue;result.push({id:`suggested:${pair.input.id}:${pair.output.id}`,startUtcMs,endUtcMs,classification,sourceEventIds:Object.freeze([pair.input.id,pair.output.id].sort()),scheduleRefs:refsFor(interval,source)});}return Object.freeze(result.sort((a,b)=>a.startUtcMs-b.startUtcMs||a.endUtcMs-b.endUtcMs||a.id.localeCompare(b.id)));}
